---
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
      Squiz Functions MultiLineFunctionDeclaration BraceOnSameLine:
        enabled: false
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- conf/**/*
- content/**/*
- drush/**/*
- patches/**/*
- results/**/*
- scripts/**/*
- scripts/*
- tests/*
- tests/**/*
- docroot/includes/**/*
- docroot/includes/*
- docroot/misc/*
- docroot/misc/**/*
- docroot/modules/**/*
- docroot/profiles/**/*
- docroot/scripts/*
- docroot/themes/**/*
- docroot/sites/default/*
- docroot/sites/all/libraries/**/*
- docroot/sites/all/modules/contrib/**/*
- docroot/sites/all/themes/zen/**/*
- docroot/authorize.php
- docroot/cron.php
- docroot/index.php
- docroot/install.php
- docroot/test.php
- docroot/update.php
- docroot/xmlrpc.php
- docroot/sites/all/modules/osha_tmgmt_demo/*.features.*
- docroot/sites/all/modules/osha_tmgmt_demo/*.rules_defaults.*
- docroot/sites/all/modules/osha_tmgmt_demo/*.strongarm.*
- docroot/sites/all/modules/osha_tmgmt/*.features.*
- docroot/sites/all/modules/osha_tmgmt/*.rules.*
- docroot/sites/all/modules/osha_tmgmt/*.rules_defaults.*
- docroot/sites/all/modules/osha_tmgmt/*.views_default.*
