<?php
/**
 * @file
 * Code for the EU-OSHA Translation Management DEMO feature.
 */

include_once 'osha_tmgmt_demo.features.inc';

module_load_include('inc', 'osha_tmgmt_demo', 'osha_tmgmt_demo.permission');

/**
 * Implements hook_node_info().
 */
function osha_tmgmt_demo_node_info() {
  $items = array(
    'osha_tmgmt_demo_article' => array(
      'name' => 'TMGMT Article',
      'base' => 'node_content',
      'description' => 'Translatable article to showcase the EU-OSHA translation features',
      'has_title' => '1',
      'title_label' => 'Title',
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
